# 1) Write a python function which take a dataframe as input and deals
# with the issue of outliers in all the continuous variables.

In [3]:
#Importing libraries
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
#Read data
df = pd.read_csv("Task1.csv")
df.head()

Sr no     Name  Person height
0    NaN      NaN            NaN
1    1.0    Rahul            5.9
2    2.0     Amit            5.2
3    3.0  Sanjana            5.1
4    4.0   Anjali            5.5

In [5]:
df['Person height'].quantile(0.95)
#we will store varaible called maximum thershold.

9.689999999999998

In [6]:
#Detect Outliers by Using Percentile method
max_thresold = df['Person height'].quantile(0.95)
max_thresold
#9.68 is 95% quantile

9.689999999999998

In [7]:
#Detecting max Outlier
df[df['Person height']>max_thresold]


Sr no    Name  Person height
10   10.0  Fandry           14.5

In [8]:
#Detecting min outlier Min threshold quantile 0.05
min_thresold = df['Person height'].quantile(0.05)
min_thresold

3.6050000000000004

In [9]:
#Dectecting min outlier
df[df['Person height']<min_thresold]


Sr no   Name  Person height
13   13.0  Jonas            1.2

In [10]:
#Removing Outliers
df[(df['Person height']<max_thresold) & (df['Person height']>min_thresold)]


Sr no      Name  Person height
1     1.0     Rahul            5.9
2     2.0      Amit            5.2
3     3.0   Sanjana            5.1
4     4.0    Anjali            5.5
5     5.0    Salman            4.9
6     6.0      Mike            5.4
7     7.0     Salim            6.2
8     8.0     Harsh            6.5
9     9.0   Jasmine            7.1
11   11.0      Anna            6.1
12   12.0      Adam            5.6
14   14.0  Daruwala            5.5

In [11]:
#As above we can see max and min outlier is removed

# 2) Write a function in python that inputs a dataframe and identify which columns have date in them. Using these date columns
# make new columns which are difference between these columns taking 2 at a time.

In [12]:
  #Read data
df = pd.read_csv("countryLockdowndates.csv")
df.head()                           

Country/Region Province        Date  Type  \
0    Afghanistan      NaN  24/03/2020  Full   
1        Albania      NaN  08/03/2020  Full   
2        Algeria      NaN  24/03/2020  Full   
3        Andorra      NaN  16/03/2020  Full   
4         Angola      NaN  24/03/2020  Full   

                                           Reference  
0  https://www.thestatesman.com/world/afghan-govt...  
1  https://en.wikipedia.org/wiki/2020_coronavirus...  
2  https://www.garda.com/crisis24/news-alerts/325...  
3  https://en.wikipedia.org/wiki/2020_coronavirus...  
4  https://en.wikipedia.org/wiki/2020_coronavirus...

In [13]:
pd.to_datetime

<function pandas.core.tools.datetimes.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=None, format=None, exact=True, unit=None, infer_datetime_format=False, origin='unix', cache=True)>

In [15]:
df.Date

0      24/03/2020
1      08/03/2020
2      24/03/2020
3      16/03/2020
4      24/03/2020
          ...    
302    16/03/2020
303    19/03/2020
304    05/03/2020
305           NaN
306    27/03/2020
Name: Date, Length: 307, dtype: object

In [32]:
#Added new coloumn of date
Date= ['25/04/2020', '21/02/2022', '31/12/2019', '12/4/2019',]
df = pd.DataFrame(Date)
df.head()

0
0  25/04/2020
1  21/02/2022
2  31/12/2019
3   12/4/2019

# 3) Write a function in python that take dataframe as input and drop columns 
# having Pearson correlation more than 0.85

In [35]:
# load libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris


In [36]:
#iris.csv
iris = load_iris()

In [37]:
# Create features and target
X = iris.data; print(); print(X)
y = iris.target; print(); print(y)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4

In [38]:
# Convert feature matrix into DataFrame
df = pd.DataFrame(X)

In [40]:
# View the data frame
print(); print(df)


       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [41]:
# Create correlation matrix
corr_matrix = df.corr().abs()
print(); print(corr_matrix)


          0         1         2         3
0  1.000000  0.117570  0.871754  0.817941
1  0.117570  1.000000  0.428440  0.366126
2  0.871754  0.428440  1.000000  0.962865
3  0.817941  0.366126  0.962865  1.000000


In [44]:
# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),
                                      k=1).astype(np.bool))
print(); print(upper)


    0        1         2         3
0 NaN  0.11757  0.871754  0.817941
1 NaN      NaN  0.428440  0.366126
2 NaN      NaN       NaN  0.962865
3 NaN      NaN       NaN       NaN


In [47]:
 # Find index of feature columns with correlation greater than 0.85
to_drop = [column for column in upper.columns if any(upper[column] > 0.85)]
print(); print(to_drop)


[2, 3]


In [48]:
# Drop columns with correlation greater than 0.85
df1 = df.drop(df.columns[to_drop], axis=1)
print(); print(df1)



       0    1
0    5.1  3.5
1    4.9  3.0
2    4.7  3.2
3    4.6  3.1
4    5.0  3.6
..   ...  ...
145  6.7  3.0
146  6.3  2.5
147  6.5  3.0
148  6.2  3.4
149  5.9  3.0

[150 rows x 2 columns]
